#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mwan3[-1]
	add ucitrack mwan3
	set ucitrack.@mwan3[-1].init=mwan3
	commit ucitrack
	delete firewall.mwan3
	set firewall.mwan3=include
	set firewall.mwan3.type=script
	set firewall.mwan3.path=/var/etc/mwan3.include
	set firewall.mwan3.reload=1
	commit firewall
EOF
exit 0
